api/urls.py
from django.urls import path
from rest_framework_simplejwt import views as jwt_views
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name='api'
urlpatterns = [
    path('test-cors/', views.test_cors_view, name='test_cors_view'),
    path('login/', jwt_views.TokenObtainPairView.as_view(), name ='login'),
    path('login/refresh/', jwt_views.TokenRefreshView.as_view(), name ='login_refresh'),

    path('login-user/', views.loginUser, name ='login_user'),
    path('get-user-details/', views.getUserDetails, name ='get_user_details'),
    path('logout-user/', views.logoutUser, name ='logout_user'),

    path('get-response/', csrf_exempt(views.getResponse), name ='getResponse')
]

chatBot/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('message_store', csrf_exempt(views.messageStore), name='message_store'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),

    path('', include('superuser.urls')),
    
    path('api/', include('api.urls')),
    
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]


handler404 = 'chatBot.views.custom_page_not_found_view'
handler500 = 'chatBot.views.custom_error_view'
handler403 = 'chatBot.views.custom_permission_denied_view'
handler400 = 'chatBot.views.custom_bad_request_view'

superuser/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'superuser'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('service-texts', views.serviceTexts, name='serviceTexts'),
    path('chat', views.chat, name='chat')
]

templates/portal/partials/_footer.html
<footer id="footer" class="footer">
  <div class="copyright">
    {% now "Y" %} &copy; Copyright <strong><span>{{project_name}}</span></strong>. All Rights Reserved
  </div>
  <div class="credits">
    Developed by <a target="_blank" href="https://spaatech.net/">SPAATech Solutions India Pvt. Ltd.</a>
  </div>
</footer>

templates/portal/partials/_header.html
{% load static %}

<header id="header" class="header fixed-top d-flex align-items-center text-white" style="background-color: #ffffff;">
  <div class="d-flex align-items-center justify-content-between">
    <a href="{% url 'superuser:dashboard' %}" class="logo d-flex align-items-center">
      <img src="{% static 'images/logo.png' %}" alt="">
    </a>
    <i class="bi bi-list toggle-sidebar-btn"></i> <span class="companyTxt">{{client_name}}</span>
  </div>
  <!-- End Logo -->

  <nav class="header-nav ms-auto">
    <ul class="d-flex align-items-center">
      <li class="nav-item dropdown pe-3">

        <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
          <img src="{% static 'images/no_user.png' %}" alt="Profile" class="rounded-circle">
          <span class="d-none d-md-block dropdown-toggle ps-2">{{request.user.first_name}}
            {{request.user.last_name}}</span>
        </a>
        <!-- End Profile Iamge Icon -->

        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
          <li class="dropdown-header">
            <h6>{{request.user.first_name}} {{request.user.last_name}}</h6>
            <span>{{request.user.email}}</span>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>

          <li>
            <a class="dropdown-item d-flex align-items-center" href="#">
              <i class="bi bi-person"></i>
              <span>My Profile</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>

          <!-- <li>
            <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
              <i class="bi bi-gear"></i>
              <span>Account Settings</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li> -->

          <!-- <li>
            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
              <i class="bi bi-question-circle"></i>
              <span>Need Help?</span>
            </a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li> -->

          <li>
            <a class="dropdown-item d-flex align-items-center logout" href="javascript:void(0)">
              <i class="bi bi-box-arrow-right"></i>
              <span>Sign Out</span>
            </a>
          </li>

        </ul>
        <!-- End Profile Dropdown Items -->
      </li>
      <!-- End Profile Nav -->

    </ul>
  </nav>
  <!-- End Icons Navigation -->

</header>

<script>
  $(document).on('click', '.logout', function () {
    $.ajax({
      type: "POST",
      url: "{% url 'api:logout_user' %}",
      headers: {
        'Content-Type': 'application/json',
        'Authorization': sessionStorage.getItem("accessToken"),
      },
      success: function (response) {
        sessionStorage.removeItem("accessToken");
        message_store(response.message, 'success', "{% url 'signin' %}");
      },
      error: function (error) {
        message_store(error.responseJSON.detail, 'error');
      }
    });
  })
</script>

templates/portal/partials/_sidebar.html
<aside id="sidebar" class="sidebar">

  <ul class="sidebar-nav" id="sidebar-nav">

    <li class="nav-item">
      <a class="nav-link {% if request.path == '/dashboard' %}active{% endif %}" href="{% url 'superuser:dashboard' %}">
        <i class="bi bi-grid"></i>
        <span>Dashboard</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link {% if request.path == '/service-texts' %}active{% endif %}" href="{% url 'superuser:serviceTexts' %}">
        <i class="bi bi-file-ruled-fill"></i>
        <span>Service Texts</span>
      </a>
    </li>
  </ul>
</aside>